"""Driving Cisco TRex: starting it, configuring it, and reading its counters.

WHAT THIS FILE IS
    Everything to do with the traffic generator. TRex is two programs -- a C++
    engine that owns the network interfaces and makes the packets, and a Python
    client that tells it what to do over a socket. This file starts the first
    and speaks to the second.

WHY THE ENGINE RUNS IN "SOFTWARE" MODE
    TRex is normally a DPDK application that takes over real network cards. We
    have no spare cards, so it drives ordinary Linux interfaces through
    AF_PACKET instead. That costs throughput but is the only way to keep the
    whole benchmark on one machine.

    Two consequences worth knowing. Interfaces are named plainly in the
    configuration file, with no prefix: TRex decides what an entry means by
    looking for a colon, so anything without one is treated as a Linux
    interface and anything with one is parsed as a hardware address. And a
    software interface has no multiple receive queues, so the stateful engine
    refuses to start with more than one traffic thread.

WHY THE ENGINE STAYS UP ACROSS THE WHOLE SWEEP
    Started once and driven through its client, rather than relaunched for each
    data point. The sweep then costs one startup instead of a dozen, and the
    counters come back as structured data instead of being scraped out of
    console text whose format changes between versions.

A TRAP THIS FILE GUARDS AGAINST
    The `t-rex-64` command is a shell script that runs the real binary as a
    child rather than replacing itself with it. Signalling only the process we
    launched kills the wrapper and leaves the engine running, holding its
    control port, so the next run fails with an unrelated error. Everything is
    therefore started in its own process group and signalled as a group.
"""

from __future__ import annotations

import os
import signal
import socket
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import network_topology as net

HERE = Path(__file__).resolve().parent

# Pinned deliberately. TRex is a measuring instrument, not a dependency: its
# exact build is part of every number this produces, so changing the version
# invalidates previously collected results. Bumping it should be a conscious
# act, with fresh baselines taken afterwards.
TREX_VERSION = "v3.08"
TREX_URL = f"https://trex-tgn.cisco.com/trex/release/{TREX_VERSION}.tar.gz"

CONTROL_PORT = 4501


def trex_directory() -> Path:
    """Find TRex, unpacked beside this program at the pinned version.

    That is the whole contract: no environment variables, no shared cache, no
    search path. Installing it is one download and one extraction, and wrapping
    that in Python would only add a progress bar and a second thing to go wrong.
    """
    for candidate in (HERE / "trex" / TREX_VERSION, HERE / TREX_VERSION):
        if (candidate / "t-rex-64").is_file():
            return candidate

    others = list(dict.fromkeys(
        [p.parent.name for p in HERE.glob("*/*/t-rex-64")]
        + [p.parent.name for p in HERE.glob("*/t-rex-64")]))
    mismatch = ""
    if others:
        mismatch = (f"\nFound unpacked instead: {', '.join(others)}\n"
                    f"This benchmark is pinned to {TREX_VERSION}; the generator's\n"
                    f"build is part of every measurement, so change TREX_VERSION\n"
                    f"deliberately and re-take your baselines.\n")

    sys.exit(
        f"TRex {TREX_VERSION} is not unpacked here ({HERE}).\n"
        f"  looked for: trex/{TREX_VERSION}/t-rex-64\n"
        f"              {TREX_VERSION}/t-rex-64\n"
        f"{mismatch}\n"
        f"  mkdir -p trex\n"
        f"  wget -P trex {TREX_URL}\n"
        f"  tar -xzf trex/{TREX_VERSION}.tar.gz -C trex\n")


def write_configuration(cpus: net.CpuAllocation, path: Path) -> None:
    """Write the platform file describing our interfaces and core assignment."""
    path.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")
    path.write_text(f"""\
# GENERATED by traffic_generator.py -- rewritten on every run.
# host: {os.uname().nodename}   {now}
#
# Plain interface names, no prefix. TRex decides what an entry is by looking
# for a colon: without one it drives a Linux interface through AF_PACKET, with
# one it parses a hardware address. It also checks the interface exists in
# /sys/class/net, which is why these two live in the root namespace.
- version: 2
  interfaces: ['{net.GENERATOR_C}', '{net.GENERATOR_S}']

  # Not a real link speed. It only scales the "percent of line rate" figures
  # TRex prints, and a virtual cable has no line rate -- read the absolute
  # packets and bits per second instead and ignore every percentage.
  port_bandwidth_gb: 10

  # Destination addresses are given explicitly so the generator never has to
  # ARP, and the device under test has matching permanent neighbour entries.
  # No address resolution happens on the data path in either direction.
  port_info:
      - src_mac: {net.MAC[net.GENERATOR_C]}
        dest_mac: {net.MAC[net.DUT_C]}
        ip: {net.GENERATOR_C_IP}
        default_gw: {net.DUT_C_IP}
      - src_mac: {net.MAC[net.GENERATOR_S]}
        dest_mac: {net.MAC[net.DUT_S]}
        ip: {net.GENERATOR_S_IP}
        default_gw: {net.DUT_S_IP}

  # From this machine's topology: {cpus.physical_cores} physical cores, with the
  # generator and the software under test never sharing one.
  platform:
      master_thread_id: {cpus.control_cpu}
      latency_thread_id: {cpus.latency_cpu}
      dual_if:
        - socket: 0
          threads: [{','.join(map(str, cpus.traffic_cpus))}]

  # Kept in step with the hugepage reservation.
  limit_memory: {net.HUGEPAGES_WANTED * 2}
""")


class TrexEngine:
    """The TRex engine as a context manager: starts on entry, dies on exit."""

    def __init__(self, config: Path, cpus: net.CpuAllocation, log: Path) -> None:
        self.config, self.cpus, self.log = config, cpus, log
        self.directory = trex_directory()
        self.process: subprocess.Popen | None = None

    def __enter__(self) -> "TrexEngine":
        self._require_free_port()
        self.log_handle = self.log.open("w")
        # TRex's launcher runs a helper script under whichever `python3` is on
        # PATH unless PYTHON3 says otherwise. Handing it our own keeps the
        # engine's setup and this program on one interpreter.
        environment = {**os.environ, "PYTHON3": sys.executable}
        self.process = subprocess.Popen(
            ["./t-rex-64", "-i", "--astf", "--software", "--no-hw-flow-stat",
             "--cfg", str(self.config), "-c", str(len(self.cpus.traffic_cpus))],
            cwd=self.directory, env=environment,
            stdout=self.log_handle, stderr=subprocess.STDOUT,
            start_new_session=True)
        self._wait_until_ready()
        return self

    def __exit__(self, *exc) -> None:
        if self.process and self.process.poll() is None:
            self._signal_group(signal.SIGTERM)
            try:
                self.process.wait(timeout=15)
            except subprocess.TimeoutExpired:
                self._signal_group(signal.SIGKILL)
                self.process.wait(timeout=10)
        # The wrapper can exit before the engine does, so wait for the port to
        # actually come free rather than trusting an exit status.
        deadline = time.time() + 20
        while time.time() < deadline and self._port_in_use():
            time.sleep(0.5)
        self.log_handle.close()

    def _signal_group(self, sig: int) -> None:
        assert self.process is not None
        try:
            os.killpg(os.getpgid(self.process.pid), sig)
        except (ProcessLookupError, PermissionError):
            pass

    @staticmethod
    def _port_in_use() -> bool:
        with socket.socket() as probe:
            probe.settimeout(0.5)
            return probe.connect_ex(("127.0.0.1", CONTROL_PORT)) == 0

    def _require_free_port(self) -> None:
        if not self._port_in_use():
            return
        sys.exit(
            f"something is already listening on 127.0.0.1:{CONTROL_PORT} --\n"
            f"almost certainly a TRex engine left over from an earlier run.\n"
            f"  sudo pkill -x _t-rex-64\n"
            f"Starting anyway would fail deep inside TRex's setup script with a\n"
            f"much less readable message.")

    def _wait_until_ready(self, timeout: float = 60.0) -> None:
        process = self.process
        assert process is not None
        deadline = time.time() + timeout
        while time.time() < deadline:
            if process.poll() is not None:
                sys.exit(f"TRex exited during startup (code {process.returncode}).\n"
                         f"  log: {self.log}")
            if self._port_in_use():
                time.sleep(1.0)  # let it finish coming up behind the socket
                return
            time.sleep(0.5)
        sys.exit(f"TRex did not start listening within {timeout:.0f}s. log: {self.log}")

    def client(self):
        """The control client, imported from the TRex tree we are running."""
        api = self.directory / "automation" / "trex_control_plane" / "interactive"
        if str(api) not in sys.path:
            sys.path.insert(0, str(api))
        try:
            from trex.astf.api import ASTFClient  # type: ignore[import-not-found]
        except ImportError as problem:
            sys.exit(f"cannot import TRex's control client: {problem}\n"
                     f"  looked in {api}\n"
                     f"  running under {sys.executable} ({sys.version.split()[0]})")
        return ASTFClient(server="127.0.0.1")


# --- one data point --------------------------------------------------------

def group_stats(client, groups: list[str]) -> dict:
    """Per-template-group counters: what happened to each kind of connection.

    Needed because the aggregate numbers cannot show whether blocking worked.
    Blocking happens at the ClientHello, which is *after* the TCP handshake, so
    a blocked connection still completes its handshake and still counts as
    established. What separates it from an allowed one is that it never gets the
    server's reply -- visible only by looking at the groups separately.
    """
    out: dict = {}
    try:
        raw = client.get_traffic_tg_stats(groups, skip_zero=False)
    except Exception:  # noqa: BLE001 - older builds may not have groups
        return out
    for group in groups:
        side = (raw.get(group) or {}).get("client", {})
        attempted = side.get("tcps_connattempt", 0)
        # Bytes arriving from the server. A blocked connection never sees any:
        # its ClientHello is dropped, so the reply it is waiting for is never
        # sent. This is the number that actually says whether blocking worked.
        received = side.get("tcps_rcvbyte", 0)
        out[f"{group}_attempted"] = attempted
        out[f"{group}_established"] = side.get("tcps_connects", 0)
        out[f"{group}_rcvbyte"] = received
        # Server bytes per attempted connection. The server sends 1400 bytes to
        # anyone it hears from, so this reads directly: near 1400 means the
        # connections completed, near 0 means their ClientHello never arrived.
        # For the blocked group that is the whole measurement -- near 0 is
        # blocking working, and any climb towards 1400 is hostnames getting
        # through.
        out[f"{group}_bytes_per_conn"] = (received / attempted) if attempted else None
    return out


def cpu_by_role(before: dict, after: dict, cpus: net.CpuAllocation) -> dict:
    """Machine-wide CPU use, grouped by what each CPU was reserved for.

    The generator reports its own CPU figure, but that says nothing about the
    rest of the machine -- and a generator quietly sitting at 97% while the
    software under test is barely working produces numbers that describe the
    generator. These three columns make that visible instead of inferred.
    """
    busy = net.cpu_busy(before, after)
    out: dict = {}
    for role, members in cpus.roles().items():
        values = [busy[c] for c in members if c in busy]
        out[f"cpu_{role}_pct"] = (sum(values) / len(values)) if values else None
        out[f"cpu_{role}_max_pct"] = max(values) if values else None
    out["cpu_busiest"] = ",".join(
        f"{c}:{busy[c]:.0f}" for c in sorted(busy, key=lambda k: -busy[k])[:4])
    return out


def measure_one_point(client, multiplier: float, seconds: float,
                      latency_pps: int, sample_queue=None,
                      groups: list[str] | None = None,
                      cpus: net.CpuAllocation | None = None) -> tuple[dict, dict]:
    """Run traffic at one rate and return (summary, raw counters).

    The sample is taken near the end of the traffic window, not after it: the
    numbers that matter are rates, and a rate read after traffic stops is zero.

    `sample_queue`, if given, is called at that same moment. The kernel's queue
    depth is an instantaneous value, so reading it after the run always returns
    zero and tells you nothing.
    """
    client.clear_stats()
    started = time.time()
    cpu_before = net.cpu_times() if cpus else None
    # The latency stream runs alongside the traffic, so the percentiles are
    # measured under load rather than on an idle path. It uses addresses inside
    # the routed ranges, and the queue rule matches by input interface, so these
    # packets take the same full trip through userspace as everything else.
    client.start(mult=multiplier, duration=seconds, latency_pps=latency_pps)
    time.sleep(max(1.0, seconds * 0.85))

    # Everything sampled at the same instant, near the end of the traffic
    # window: rates read after traffic stops are zero, and a queue depth read
    # then is always zero too.
    queue_depth = sample_queue() if sample_queue else None
    machine = (cpu_by_role(cpu_before, net.cpu_times(), cpus)
               if cpus and cpu_before else {})
    stats = client.get_stats()
    per_group = group_stats(client, groups) if groups else {}
    client.wait_on_traffic()

    summary = summarise(stats, time.time() - started)
    summary["queue_depth"] = queue_depth
    summary.update(per_group)
    summary.update(machine)
    raw = {"aggregate": stats, "groups": per_group}
    return summary, raw


def summarise(stats: dict, elapsed: float) -> dict:
    """Flatten one sample into the fields we report.

    Explicit paths, never a search by name. The structure is known, and
    searching risks picking up the client side's own transmit rate when the
    global one was meant -- a mistake that reads as plausible and is invisible.
    """
    overall = stats.get("global", {})
    client_side = stats.get("traffic", {}).get("client", {})

    attempted = client_side.get("tcps_connattempt", 0)
    established = client_side.get("tcps_connects", 0)

    return {
        # Connections per second is the headline for software that does its
        # work once per connection. Bandwidth is secondary but reported because
        # it is what people ask for.
        "connections_per_sec": overall.get("tx_cps"),
        "gbps_sent": _to_gbps(overall.get("tx_bps")),
        "gbps_received": _to_gbps(overall.get("rx_bps")),
        "packets_per_sec": overall.get("tx_pps"),
        "active_connections": overall.get("active_flows"),
        "connections_attempted": attempted,
        "connections_established": established,
        # Below the point where blocking breaks down this tracks the allowed
        # share of the traffic profile. If it climbs towards 100% as load rises,
        # connections that should be blocked are completing.
        "established_pct": (100.0 * established / attempted) if attempted else None,
        "generator_cpu_pct": overall.get("cpu_util"),
        "generator_tx_ratio": client_side.get("m_tx_ratio"),
        "elapsed_s": elapsed,
        **latency_percentiles(stats),
    }


def _to_gbps(bits_per_sec) -> float | None:
    return None if bits_per_sec is None else float(bits_per_sec) / 1e9


def latency_percentiles(stats: dict) -> dict:
    """Round-trip latency from the generator's own latency stream.

    This is per-packet time through whatever sits between the two interfaces --
    including, when the inspector is running, the full trip out to userspace and
    back. It is NOT the time a ClientHello spends held while its connection is
    decided; only the inspector can see that, and measuring it needs timestamps
    inside the inspector itself.

    TRex reports a bucketed histogram rather than percentiles, and its exact
    shape varies between versions, so this reads defensively and leaves fields
    empty rather than inventing a number. The whole block is written to the raw
    JSON regardless.
    """
    latency = stats.get("latency") or {}
    buckets: dict[float, int] = {}
    worst = 0.0
    errors = 0

    for key, port in latency.items():
        if not isinstance(port, dict):
            continue
        if key == "global":
            for name, value in port.items():
                if isinstance(value, (int, float)) and name != "old_flow":
                    errors += int(value)
            continue
        histogram = port.get("hist") or {}
        worst = max(worst, float(histogram.get("max_usec") or 0))
        for entry in histogram.get("histogram") or []:
            try:
                bucket = float(entry["key"])
                buckets[bucket] = buckets.get(bucket, 0) + int(entry["val"])
            except (KeyError, TypeError, ValueError):
                continue

    def percentile(fraction: float):
        total = sum(buckets.values())
        if not total:
            return None
        target, seen = total * fraction, 0
        for bucket in sorted(buckets):
            seen += buckets[bucket]
            if seen >= target:
                return bucket
        return max(buckets)

    return {
        "latency_p50_us": percentile(0.50),
        "latency_p99_us": percentile(0.99),
        "latency_max_us": worst or None,
        "latency_errors": errors,
    }
